# v-BAZ :: Alpine overlay (apkovl) builder
# Assembles the local backup / auto-config tarball that Alpine loads at boot.
# It carries the first-boot provisioner and its configuration so the install
# onto VBAZ_ROOT + the KVM/libvirt/QEMU setup run unattended.

Set-StrictMode -Version Latest

function Build-VBazApkovl {
    param(
        [Parameter(Mandatory)][hashtable]$Config,
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$StageDir,
        [securestring]$Password  # optional; if omitted, first-login password change is forced
    )

    Write-VBazLog 'Building Alpine overlay (apkovl)' -Level STEP
    $work = Join-Path $StageDir 'apkovl'
    if (Test-Path $work) { Remove-Item -Recurse -Force $work }
    New-Item -ItemType Directory -Force -Path $work | Out-Null

    # 1) Base overlay tree (etc/local.d/... + runlevel hook source).
    Copy-Item -Recurse -Force (Join-Path $RepoRoot 'alpine\overlay\*') $work

    # 2) Provisioner + support files land under etc/vbaz.
    $vbazEtc = Join-Path $work 'etc\vbaz'
    New-Item -ItemType Directory -Force -Path $vbazEtc | Out-Null
    Copy-Item -Force (Join-Path $RepoRoot 'alpine\provision\vbaz-provision.sh') (Join-Path $vbazEtc 'vbaz-provision.sh')
    Copy-Item -Force (Join-Path $RepoRoot 'alpine\provision\packages.list')     (Join-Path $vbazEtc 'packages.list')
    Copy-Item -Force (Join-Path $RepoRoot 'alpine\answers\vbaz.answers')         (Join-Path $vbazEtc 'vbaz.answers')

    # 3) Render environment consumed by the provisioner. Use LF line endings.
    $envText = @(
        "# generated by Install-VBaz.ps1",
        "VBAZ_ROOTLABEL='$($Config.RootPartitionLabel)'",
        "VBAZ_ROOTTYPE='$($Config.RootPartitionType.ToLower())'",
        "VBAZ_SWAPLABEL='$($Config.SwapPartitionLabel)'",
        "VBAZ_HOSTNAME='$($Config.Hostname)'",
        "VBAZ_USERNAME='$($Config.Username)'",
        "VBAZ_TIMEZONE='$($Config.Timezone)'",
        "VBAZ_BRANCH='$($Config.AlpineBranch)'",
        "VBAZ_MIRROR='$($Config.Mirror)'",
        "VBAZ_ARCH='$($Config.Arch)'",
        "VBAZ_FLAVOR='$($Config.Flavor)'",
        "VBAZ_ESPSUBDIR='$($Config.EspSubdir)'",
        "VBAZ_PACKAGE_SETS='$($Config.PackageSets -join ' ')'"
    ) -join "`n"
    Set-Content -Path (Join-Path $vbazEtc 'vbaz.env') -Value ($envText + "`n") -Encoding Ascii -NoNewline

    # 4) Optional password. If provided we drop a root-only plaintext file the
    #    provisioner consumes then shreds. WARNING: this file briefly lives on
    #    the unencrypted ESP. Default (no password) forces a change at first
    #    login instead — safer. See docs/SAFETY.md.
    if ($Password) {
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Password)
        $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        Set-Content -Path (Join-Path $vbazEtc 'secret.pw') -Value $plain -Encoding Ascii -NoNewline
        Write-VBazLog 'Password captured into overlay (transient; shredded on first boot). It briefly resides on the ESP.' -Level WARN
    } else {
        Write-VBazLog 'No password set: the operator account will require a password change at first login.' -Level INFO
    }

    # 5) Enable the OpenRC "local" service so etc/local.d/*.start runs at boot.
    #    Realized as a symlink in the default runlevel. Creating a symlink on
    #    Windows needs admin (we have it); bsdtar records it as a symlink.
    $rl = Join-Path $work 'etc\runlevels\default'
    New-Item -ItemType Directory -Force -Path $rl | Out-Null
    $link = Join-Path $rl 'local'
    if (-not (Test-Path $link)) {
        try {
            New-Item -ItemType SymbolicLink -Path $link -Target '/etc/init.d/local' -ErrorAction Stop | Out-Null
        } catch {
            # Fallback: a marker the provisioner uses to rc-update add local.
            Write-VBazLog 'Could not create runlevel symlink (no privilege / dev mode); provisioner will enable local service itself.' -Level WARN
            Set-Content -Path (Join-Path $vbazEtc 'enable-local') -Value '1' -Encoding Ascii
            Remove-Item $link -ErrorAction SilentlyContinue
        }
    }

    # 6) Pack it. Windows 10+ ships bsdtar as `tar`. Alpine wants gzip'd tar
    #    with paths relative to the overlay root.
    $out = Join-Path $StageDir 'vbaz.apkovl.tar.gz'
    if (Test-Path $out) { Remove-Item -Force $out }
    if ($script:VBazDryRun) {
        Write-VBazLog "DRY-RUN: would pack $work -> $out" -Level WARN
        return $out
    }
    Push-Location $work
    try {
        & tar --format=gnutar -czf $out .
        if ($LASTEXITCODE -ne 0) { throw "tar failed packing the apkovl (exit $LASTEXITCODE)." }
    } finally { Pop-Location }
    Write-VBazLog "apkovl built: $out" -Level OK
    return $out
}
